apiVersion: v1
kind: ReplicationController                         # 副本控制器RC
metadata:
    name: mysql                                     # RC 的名称，全局唯一
spec:
    replicas: 1                                     # Pod 副本期待数量
    selector:
        app: mysql                                  # 符合目标的P od 拥有此标签
    template:                                       # 根据此模板创建Pod 的副本（实例）
        metadata:
            labels:
                app: mysql                          # Pod 副本拥有的标签，对应RC 的Selector
        spec:
            containers:                             # Pod 内容器的定义部分
            -   name: mysql                         # 容器的名称
                image: mysql                        # 容器对应的Docker Image
                ports:
                -   containerPort: 3306             # 容器应用监听的端口号
                env:                                # 注入容器内的环绕变量
                -   name: MYSQL_ROOT_PASSWORD
                    value: "123456"
